version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        # Update the VARIANT arg to pick a Java version: 11, 16
        VARIANT: 11
        # Options
        INSTALL_MAVEN: "false"
        INSTALL_GRADLE: "false"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
    command: sleep infinity
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./:/workspace
      - .m2/:/home/vscode/.m2
      - .vscode-server/:/home/vscode/.vscode-server
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:4.30
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - postgres
