@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/security/auth
@accessToken = {{login.response.body.$.accessToken}}

// @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

###

// @name check
GET {{baseUrl}}/check
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}
