@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/security/user

// @name create
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json

{
  "username": "username1",
  "password": "password",
  "fullName": "fullName",
  "email": "email@domain.com"
}
