@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/security/user
@userId = {{create.response.body.$.id}}

// @name create
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json

{
  "username": "username1",
  "password": "password",
  "fullName": "fullName",
  "email": "email@domain.com"
}

###

// @name update
PUT {{baseUrl}}/{{userId}}
Accept: application/json
Content-Type: application/json

{
   "fullName": "fullName2",
   "email": "email2@domain.com"
}
